### ISSUE TITLE
Dance / Helix keybindings: `<n> g g` doesnt work

### ISSUE THREAD

**Issue by forivall** [imawizard/dotfiles#1]
I solved it with this change: https://github.com/forivall/dotfiles/commit/4cb921f1e1ee4f64adc6db8170bace9520e25aef - you have to pass through the `count` variable through the menu (note i made a mistake in the when clause for the `select` mode version from yank/pasting)

**Comment by imawizard** [comment]
Thanks for the fix, Emily.
